version: '3'
services:
  postgres:
    image: postgres:16rc1-alpine3.18
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: salesapi
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine3.18
    ports:
      - '6379:6379'
  salesapi:
    build: ./
    working_dir: /app
    depends_on:
      - postgres
      - redis
    ports:
      - '3333:3333'
    command:
      - sh
      - -c
      - |
        npm run typeorm migration:run && npm run start:dev
