version: '3'
services:
  pgsqldatabase:
    build: .docker/postgres
    container_name: salesapi-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: salesapi

  redis:
    image: 'bitnami/redis:latest'
    container_name: salesapi-redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - pgsqldatabase

  pgadmin:
    image: dpage/pgadmin4
    container_name: salesapi-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - pgsqldatabase

  salesapi:
    build: ./
    container_name: salesapi
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    restart: on-failure
    depends_on:
      - pgsqldatabase
      - redis
    command:
      - sh
      - -c
      - npm run typeorm -- -d src/shared/infra/typeorm/index.ts migration:run && npm run start:dev
